apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-http-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: tincher/go-hello-world:latest
        ports:
        - containerPort: 8080

